import { PizzaCrust } from '../models/pizza-crust';
export const smallHandTossedPizza = new PizzaCrust({
  "name": "Small (10\") Hand Tossed Pizza",
  "code": "10SCREEN",
  "description": "Garlic-seasoned crust with a rich, buttery taste.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT",
    "GO",
    "NGO"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "Rd",
    "R",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const mediumHandTossedPizza = new PizzaCrust({
  "name": "Medium (12\") Hand Tossed Pizza",
  "code": "12SCREEN",
  "description": "Garlic-seasoned crust with a rich, buttery taste.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT",
    "GO",
    "NGO"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const mediumThinPizza = new PizzaCrust({
  "name": "Medium (12\") Thin Pizza",
  "code": "12THIN",
  "description": "Thin enough for the optimum crispy to crunchy ratio and square cut to be perfectly sharable.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "PIECT",
    "SQCT",
    "UNCT",
    "RGO",
    "NOOR"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const largeNewYorkStylePizza = new PizzaCrust({
  "name": "Large (14\") New York Style Pizza",
  "code": "PBKIREZA",
  "description": "Hand-stretched thin and cut into six big, foldable slices offering a perfect balance of sauce, cheese, and crust in every bite.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const largeHandTossedPizza = new PizzaCrust({
  "name": "Large (14\") Hand Tossed Pizza",
  "code": "14SCREEN",
  "description": "Garlic-seasoned crust with a rich, buttery taste.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT",
    "GO",
    "NGO"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const largeThinPizza = new PizzaCrust({
  "name": "Large (14\") Thin Pizza",
  "code": "14THIN",
  "description": "Thin enough for the optimum crispy to crunchy ratio and square cut to be perfectly sharable.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "PIECT",
    "SQCT",
    "UNCT",
    "RGO",
    "NOOR"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const xLargeNewYorkStylePizza = new PizzaCrust({
  "name": "X-Large (16\") New York Style Pizza",
  "code": "P16IBKZA",
  "description": "Hand-stretched thin and cut into six big, foldable slices offering a perfect balance of sauce, cheese, and crust in every bite.",
  "surcharge": "-0.26",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const smallGlutenFreeCrustPizza = new PizzaCrust({
  "name": "Small (10\") Gluten Free Crust Pizza",
  "code": "P10IGFZA",
  "description": "Domino's pizza made with a Gluten Free Crust.",
  "surcharge": "1",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const mediumHandmadePanPizza = new PizzaCrust({
  "name": "Medium (12\") Handmade Pan Pizza",
  "code": "P12IPAZA",
  "description": "Two layers of cheese, toppings to the edge, baked in a pan for a crust that is golden and crispy with a buttery taste.",
  "surcharge": "1.5",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

export const mediumNewYorkStylePizza = new PizzaCrust({
  "name": "Medium (12\") New York Style Pizza",
  "code": "P12IBKZA",
  "description": "Hand-stretched thin and cut into six big, foldable slices offering a perfect balance of sauce, cheese, and crust in every bite.",
  "surcharge": "0",
  "allowedCookingInstructions": [
    "WD",
    "NB",
    "PIECT",
    "SQCT",
    "UNCT"
  ],
  "availableToppings": [
    "B",
    "Bq",
    "C",
    "Cp",
    "Cs",
    "Du",
    "E",
    "Fe",
    "G",
    "H",
    "Ht",
    "J",
    "K",
    "M",
    "N",
    "O",
    "P",
    "Pm",
    "R",
    "Rd",
    "S",
    "Sa",
    "Si",
    "Td",
    "X=0:0.5:1:1.5",
    "Xf=0:0.5:1:1.5",
    "Xm=0:0.5:1:1.5",
    "Xw=0:0.5:1:1.5",
    "Z"
  ]
});

